services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}

    ports:
      - "8501:8501"
    env_file:
      - .env

    depends_on:
      - vectordb

  vectordb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - vector_volume:/qdrant/storage


volumes:
  vector_volume: